/*

 EXPORT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Ball8x8[] =
{
  0x3C,0x3C,0x5E,0x62,0xB3,0xC1,0xB3,0xC1,
  0xBF,0xC1,0x9D,0xE3,0x42,0x7E,0x3C,0x3C
};

/* End of EXPORT.C */
